// document image set actions
export const FETCH_DOCUMENT_IMAGES = "FETCH_DOCUMENT_IMAGES";
export const SET_LOADING_STATE = "SET_LOADING_STATE";
export const ADD_IMAGE = "ADD_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const SET_RUNNING_STATE = "SET_RUNNING_STATE";
export const UPDATE_IMAGE_DATA = "UPDATE_IMAGE_DATA";

// image actions
export const SELECT_IMAGE = "SELECT_IMAGE";
export const SET_IMAGE_DATA = "SET_IMAGE_DATA";
export const UPDATE_DOCUMENT_STAFF = "UPDATE_DOCUMENT_STAFF";
export const UPDATE_STAFF_SYMBOLS = "UPDATE_STAFF_SYMBOLS";
export const TAG_VOICE = "TAG_VOICE";
export const TAG_BOOKEND = "TAG_BOOKEND";
export const DELETE_POINT_OF_INTEREST = "DELETE_POINT_OF_INTEREST";

// running states
export const RUNNING_STATE_STOPPED = "RUNNING_STATE_STOPPED";
export const RUNNING_STATE_RUNNING = "RUNNING_STATE_RUNNING";

// loading states
export const LOADING_STATE_UNLOADED = "LOADING_STATE_UNLOADED";
export const LOADING_STATE_LOADING = "LOADING_STATE_LOADING";
export const LOADING_STATE_LOADED = "LOADING_STATE_LOADED";
